### ISSUE TITLE
Default value for static

### ISSUE THREAD

**Issue by ovv** [pyslackers/ansible-role-nginx#8]
At the moment the role fail if `static` is not defined. IMO static should not be required and by `False` by default.

we could add something like this in the template:
```
{% if static is not defined %}
    {% set static = False %}
{% endif %}
```

**Comment by mattrasband** [comment]
💯 % agree, though I think we can probably do it more elegantly than defining it if it's not set. We'll have to check the options, but either setting it to empty in the defaults (thereby making it falsy) or something else

**Comment by ovv** [comment]
it's in a dict structure 
```
sites:
  sirbot:
    domains:
      - sirbot.staging.pyslackers.com
    port: 8080
    ssl: false
    email: "{{ email }}"
    staging: true
    static: ''
```

so I don't think we can set that as a classic default. We could also do it with a nested `if` I believe
